### ISSUE TITLE
[Necromancy Skills] Skeletons Unable to Deal Damage

### ISSUE THREAD

**Issue by TRober18** [sinai-dev/Outward-Mods#10]
While the mod otherwise works, at the moment, for both the version on Nexus as well as the version on Thunderstore, the skeletons seem incapable of dealing any damage through normal attacks. Note that they do deal impact damage and the elemental vulnerability build-up on their weapons seems to be applying.

[output_log.txt](https://github.com/sinai-dev/Outward-Mods/files/7234235/output_log.txt)

**Comment by sinai-dev** [comment]
Thanks, bug was in SideLoader. Fixed now if you update your SL version.
