### ISSUE TITLE
Mana Bow, Multiplayer, no fast shooting possible.

### ISSUE THREAD

**Issue by BeIeriand** [sinai-dev/Outward-Mods#11]
When using the Mana Bow in multiplayer (I am **not** the host).
I can shoot 1 arrow and then I'll have to wait something between 3-7sec before I can shoot another one.
In single player I don't have that problem. I think it has something to do with loading/updating new arrows into my inventory.
While it shows 1 arrow in the bottom left I can shoot. If it shows nothing I'll have to wait till it updates.
I am not sure if there is a way to fix this problem or if this is know already.

I enjoy your mods a lot. Thanks for your work!

**Comment by sinai-dev** [comment]
This was a compatibility issue with raid mode, should be fixed in the latest version, thanks :)
