### ISSUE TITLE
MultipleQuickBarSlots - Loss of Item Binds on bag drop

### ISSUE THREAD

**Issue by cregham** [sinai-dev/Outward-Mods#12]
Issue when using controller, don't know if applicable to keyboard and mouse as well but I imagine it is.

Current Behavior:
1. Assign items (bed roll is a good example) to quick bar slots. 
2. Drop bag
3. Change quick bar slot and back
4. Item quick slots cleared

Expected Behavior
1. Assign items to quick bar slots. 
2. Drop bag
3. Change quick bar slot and back again
4. Item quick slots are greyed out.
5. Pick bag up
6. Quick slots are available for use again

Just makes a utility quick slot bar difficult to maintain

**Comment by sinai-dev** [comment]
Thanks, I changed the way quickslots are saved (you'll need to re-bind them again, sorry!) and it seems to have fixed the issue.
