### ISSUE TITLE
Multiple Quickslot Bars and Mini Map Conflict

### ISSUE THREAD

**Issue by Sir-AJ** [sinai-dev/Outward-Mods#13]
I have several problems using your mod - Multiple Quickslot Bars (great by the way!)
Main problem is a conflict between mini map and the **_next_** quickslot key (this hides mini map and does not bring up next bar)
The **_previous_**  works fine so the error is not catastrophic. 

I realize this could be a problem with the mini map mod and not your problem but i thought id let ya know.
I just updated to your new version and still have same problem!

Thanks!

**Comment by sinai-dev** [comment]
Reset your keybinds or delete your Outward/Player0keymappings.xml file

**Comment by Sir-AJ** [comment]
Deleting the map file worked - you da man!
Thanks!
