### ISSUE TITLE
[Save Migrator] Weapons Disappearing After Unequipping

### ISSUE THREAD

**Issue by SubduedRhombus** [sinai-dev/Outward-Mods#15]
Hi,

After migrating my save file over, any weapon I unequip, whether I obtained it before or after the migration, will disappear from my inventory. I've attempted it about 5 times and happens each time. It might also happen with clothes too, but I haven't tried it yet.

**Comment by sinai-dev** [comment]
This is not caused by Save Migrator, there is likely another mod causing that issue.
