### ISSUE TITLE
Blacksmith toolbox not working

### ISSUE THREAD

**Issue by Sir-AJ** [sinai-dev/Outward-Mods#18]
I get the following error message in the log file

[Message:SideLoader] SL Setup took 7.330891 seconds
[Warning:SideLoader] Exception invoking callback! Checking for InnerException...
[Message:SideLoader] TargetInvocationException: Exception has been thrown by the target of an invocation.
[Warning:SideLoader] ---- Inner-most exception: ----
[Message:SideLoader] NullReferenceException: Object reference not set to an instance of an object
[Message:SideLoader]   at BlacksmithsToolbox.BlacksmithsToolbox.OnPacksLoadedSetup () [0x00011] in <956fbd2f6a5c436485ef1a88d7cc7074>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <df7127ba07dc446d9f5831a0ec7b1d63>:0 
[Message:SideLoader] Finished invoking OnPacksLoaded.
[Message:SideLoader] Loaded UI bundle

Any thoughts?
Thanks!

**Comment by sinai-dev** [comment]
- Did you install this manually?
- Are you on Definitive Edition or Vanilla?
- What version of the mods are you using?

Please don't post partial logs, full logs are always more helpful.

**Comment by Sir-AJ** [comment]
I did install it manually.
I am using the definitive edition (gog)
Full log file  attached,
I am using
Sideloader ver 3.7.6
BepInEx-BepInExPack_Outward-5.4.18
Blacksmiths_toolbox 2.6.0

Thanks for your time
Regards
AJ

**Comment by Sir-AJ** [comment]
Wow - I installed it as you suggested (ie in a directory - \plugins\Blacksmithtoolbox) with sideloader in that directory (not in \plugins\sideloader)
And now all mods seem to work. The takeaway for me is to install all mods in their own directory.
Thank you for pointing me in the right direction.
Sorry to have bothered you.
Regards
AJ
