### ISSUE TITLE
DualQuickSlots by Faeryn

### ISSUE THREAD

**Issue by ShadoweCZ** [sinai-dev/Outward-Mods#19]
Hello, im not sure to whom i should write cause this is a conflict of 2 mods, so i will coppy pasta this issue to both mods :) 

when using the mods **Multiple_Quickslot_Bars by sinai-dev** and **DualQuickSlots by Faeryn** 
when i use the dual slot lets say in quickslot bar 1 on the Q slot, when i use the Q slot from quickbar 2 or 3 etc and the Q skill is on CD it will use the dualquickslot from diferent quickbar and change my weapons 

aka the dualquickslot thats used for switching weapons is mapped for Q (or any other of the slots) for all the quickbars added with multiple bars mod ... i hope its somehow understandable what i mean :) 

Could we get some sort of compactibility patch ? 
here is link for the others github:
https://github.com/Faeryn/Outward_DualQuickSlots/issues/1

**Comment by Faeryn** [comment]
I fixed it in DualQuickSlots 1.0.1
