### ISSUE TITLE
(Multiple Quickslot Bars) Quickslots become empty

### ISSUE THREAD

**Issue by MichaelAngelos** [sinai-dev/Outward-Mods#23]
This problem appeared when i tried The Three Brothers DLC,it happens in Caldera.I haven't tested much but if i go to the main menu and load my save,the quickslots i have set are fine

However,when i quit the game and load it again,the non equipped quickslot bars become empty.I have had some bugs with the DLC but i don't know what to do about this one

**Comment by sinai-dev** [comment]
Are you on definitive edition?

**Comment by MichaelAngelos** [comment]
I am,yes

**Comment by sinai-dev** [comment]
I think it's a conflict with another mod, should be fixed now if you update all mods otherwise let me know
