### ISSUE TITLE
[Minimap] Locked character up and down moving mouse

### ISSUE THREAD

**Issue by Naewt** [sinai-dev/Outward-Mods#5]
Hi, I tried the last two versions of this minimap mod and there is a bug that when I change values of the minimap config or random map change (not always) the mouse is locked for up and down moves, I tested without this mod and work fine, thanks!

P.S: thank you for create all your mods for this incredible game! Keep it up!

**Comment by sinai-dev** [comment]
I need the debug log. Recreate the issue and get the `output_log.txt` either from the Outward install folder or `%userprofile%\appdata\locallow\nine dots studio\outward\`
