### ISSUE TITLE
CustomMultiplayerLimit Sleep broken now.

### ISSUE THREAD

**Issue by wouldntsavezion** [sinai-dev/Outward-Mods#6]
CustomMultiplayerLimit Sleep broken now.

Guess it's the Three Brothers DLC

I looked at [CustomMultiplayerLimit/src/CustomMultiplayerLimit.cs](https://github.com/sinai-dev/Outward-Mods/blob/master/CustomMultiplayerLimit/src/CustomMultiplayerLimit.cs) but I can't really make sense of it. I can try fixing it if you can give me some pointers but I guess it would be simpler to just do it yourself.

**Comment by sinai-dev** [comment]
Thanks for the heads up, I'll fix it shortly just going through all the changes from the update first

**Comment by Jerry-Shaw** [comment]
Wait for a fix, thanks

**Comment by sinai-dev** [comment]
Should be fixed now, updated the releases on NexusMods. Make sure you update SideLoader and SharedModConfig too, let me know if you have any issues

**Comment by Jerry-Shaw** [comment]
Tested, all is OK now. Thanks.
