### ISSUE TITLE
Imbued Bows / Mana Bows not creating mana arrows

### ISSUE THREAD

**Issue by Tkdmaster** [sinai-dev/Outward-Mods#7]
In short, as of the latest patches, the Mana Bows are not able to create mana arrows, and instead simply use arrows you have equipped. The weapons themselves otherwise do work and do the correct damage types, etc.

**Comment by sinai-dev** [comment]
I know, havent got a chance to update this yet. Will look into it when I can, probably after I update SideLoader for new API.
